// flow-typed signature: fa9b7ba35f998ae0c7e3b980c093fa28
// flow-typed version: <<STUB>>/jsonata_v1.x/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonata' {

  declare type Callback = (error: ?InvalidExpression, value: ?any) => void;

  declare class InvalidExpression extends Error {
    code: string;
    position: number;
    token: string;
    value: string;
  }

  declare interface Jsonata {
    assign(name: string, value: any): void;
    evaluate(input: Object, bindings?: Object, callback?: Callback): void;
    registerFunction(name: string, implementation: Function, signature?: string): void;
  }

  declare function jsonata(expression: string): Jsonata;
  declare export default typeof jsonata;
}
