// flow-typed signature: 93d7756a5324f9118ea4030ac99a499b
// flow-typed version: <<STUB>>/jsonata_v^1.3.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonata/jsonata-es5' {
  declare module.exports: any;
}

declare module 'jsonata/jsonata-es5.min' {
  declare module.exports: any;
}

declare module 'jsonata/jsonata' {
  declare module.exports: any;
}

declare module 'jsonata/jsonata.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonata/jsonata-es5.js' {
  declare module.exports: $Exports<'jsonata/jsonata-es5'>;
}
declare module 'jsonata/jsonata-es5.min.js' {
  declare module.exports: $Exports<'jsonata/jsonata-es5.min'>;
}
declare module 'jsonata/jsonata.js' {
  declare module.exports: $Exports<'jsonata/jsonata'>;
}
declare module 'jsonata/jsonata.min.js' {
  declare module.exports: $Exports<'jsonata/jsonata.min'>;
}
