// flow-typed signature: 3480cc12306b93b65d20c97cc6a51dde
// flow-typed version: <<STUB>>/skeemas_v^1.2.4/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'skeemas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'skeemas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'skeemas/tests/bootstrap' {
  declare module.exports: any;
}

declare module 'skeemas/tests/index.test' {
  declare module.exports: any;
}

declare module 'skeemas/tests/json-schema-test-suite.test' {
  declare module.exports: any;
}

declare module 'skeemas/tests/json-schema-test-suite/index' {
  declare module.exports: any;
}

declare module 'skeemas/tests/plugins.test' {
  declare module.exports: any;
}

declare module 'skeemas/tests/validators/base.test' {
  declare module.exports: any;
}

declare module 'skeemas/tests/validators/number.test' {
  declare module.exports: any;
}

declare module 'skeemas/validation-context' {
  declare module.exports: any;
}

declare module 'skeemas/validation-result' {
  declare module.exports: any;
}

declare module 'skeemas/validators/array' {
  declare module.exports: any;
}

declare module 'skeemas/validators/base' {
  declare module.exports: any;
}

declare module 'skeemas/validators/boolean' {
  declare module.exports: any;
}

declare module 'skeemas/validators/deep-equal' {
  declare module.exports: any;
}

declare module 'skeemas/validators/index' {
  declare module.exports: any;
}

declare module 'skeemas/validators/null' {
  declare module.exports: any;
}

declare module 'skeemas/validators/number' {
  declare module.exports: any;
}

declare module 'skeemas/validators/object' {
  declare module.exports: any;
}

declare module 'skeemas/validators/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'skeemas/index' {
  declare module.exports: $Exports<'skeemas'>;
}
declare module 'skeemas/index.js' {
  declare module.exports: $Exports<'skeemas'>;
}
declare module 'skeemas/tests/bootstrap.js' {
  declare module.exports: $Exports<'skeemas/tests/bootstrap'>;
}
declare module 'skeemas/tests/index.test.js' {
  declare module.exports: $Exports<'skeemas/tests/index.test'>;
}
declare module 'skeemas/tests/json-schema-test-suite.test.js' {
  declare module.exports: $Exports<'skeemas/tests/json-schema-test-suite.test'>;
}
declare module 'skeemas/tests/json-schema-test-suite/index.js' {
  declare module.exports: $Exports<'skeemas/tests/json-schema-test-suite/index'>;
}
declare module 'skeemas/tests/plugins.test.js' {
  declare module.exports: $Exports<'skeemas/tests/plugins.test'>;
}
declare module 'skeemas/tests/validators/base.test.js' {
  declare module.exports: $Exports<'skeemas/tests/validators/base.test'>;
}
declare module 'skeemas/tests/validators/number.test.js' {
  declare module.exports: $Exports<'skeemas/tests/validators/number.test'>;
}
declare module 'skeemas/validation-context.js' {
  declare module.exports: $Exports<'skeemas/validation-context'>;
}
declare module 'skeemas/validation-result.js' {
  declare module.exports: $Exports<'skeemas/validation-result'>;
}
declare module 'skeemas/validators/array.js' {
  declare module.exports: $Exports<'skeemas/validators/array'>;
}
declare module 'skeemas/validators/base.js' {
  declare module.exports: $Exports<'skeemas/validators/base'>;
}
declare module 'skeemas/validators/boolean.js' {
  declare module.exports: $Exports<'skeemas/validators/boolean'>;
}
declare module 'skeemas/validators/deep-equal.js' {
  declare module.exports: $Exports<'skeemas/validators/deep-equal'>;
}
declare module 'skeemas/validators/index.js' {
  declare module.exports: $Exports<'skeemas/validators/index'>;
}
declare module 'skeemas/validators/null.js' {
  declare module.exports: $Exports<'skeemas/validators/null'>;
}
declare module 'skeemas/validators/number.js' {
  declare module.exports: $Exports<'skeemas/validators/number'>;
}
declare module 'skeemas/validators/object.js' {
  declare module.exports: $Exports<'skeemas/validators/object'>;
}
declare module 'skeemas/validators/string.js' {
  declare module.exports: $Exports<'skeemas/validators/string'>;
}
