// flow-typed signature: 771dbc288e840caac6a28d7960a908dd
// flow-typed version: <<STUB>>/skeemas_v1.x/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'skeemas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'skeemas' {
  declare module.exports: any;
}
